version: "3.9"

services:
  master_server:
    build:
      context: ./src
    volumes:
      - ./src:/app/master_server
    command: sh -c "python master_server.py"
    ports:
      - 50051:50051

  chunk_server_01:
    build:
      context: ./src
    volumes:
      - ./src:/app/chunk_server
    ports:
      - 50052:50052
    depends_on:
      - master_server

  chunk_server_02:
    build:
      context: ./src
    volumes:
      - ./src:/app/chunk_server
    ports:
      - 50053:50053
    depends_on:
      - master_server

  chunk_server_03:
    build:
      context: ./src
    volumes:
      - ./src:/app/chunk_server
    ports:
      - 50054:50054
    depends_on:
      - master_server

  chunk_server_04:
    build:
      context: ./src
    volumes:
      - ./src:/app/chunk_server
    ports:
      - 50055:50055
    depends_on:
      - master_server

  client:
    build:
      context: ./src
    volumes:
      - ./src:/app/client
    depends_on:
      - master_server
